### ISSUE TITLE
Invalid generated makeApi endpoints object, if path specific parameters are defined

### ISSUE THREAD

**Issue by pkoo** [astahmer/openapi-zod-client#78]
With the release of v1.5.x a change has been added, which will create an invalid `makeApi` endpoints object.
The previous version (1.4.20) ignored the parameters object under a PathItem.

Within the OpenAPI Spec, a `parameters` entry can exist in a PathItem, which then has to be respected for each operation in that path.
[OpenAPI spec](https://swagger.io/specification/#path-item-object)

If an OpenAPI has multiple PathItem's, each with own path-specific parameters, the generated endpoints object also has multiple wrong method definitions in it.

This is a currently (v1.5.1) generated makeApi endpoint which contains (multiple) `method: "parameters"` objects:
```js
const endpoints = makeApi([
    {
        method: "parameters",
        path: "/otherPets/:petId",
        requestFormat: "json",
        response: z.void(),
    },
    {
        method: "get",
        path: "/otherPets/:petId",
        requestFormat: "json",
        response: z.void(),
    },
    {
        method: "parameters",
        path: "/pet/:petId",
        requestFormat: "json",
        response: z.void(),
    },
    {
        method: "get",
        path: "/pet/:petId",
        requestFormat: "json",
        response: z.void(),
    },
    {
        method: "put",
        path: "/pet/:petId",
        description: `Update an existing pet by Id`,
        requestFormat: "json",
        parameters: [
            {
                name: "body",
                type: "Body",
                schema: Pet,
            },
        ],
        response: Pet,
    },
]);
```

I would like, that the path-specific parameters would be added to each `operation.parameters` object in that path.

```js
const endpoints = makeApi([
    {
        method: "get",
        path: "/otherPets/:petId",
        requestFormat: "json",
        parameters: [
            {
                name: "petId", 
                type: "Path",
                schema: z.string().min(1).max(10).required()
            }
        ],
        response: Pet,
    },
    {
        method: "get",
        path: "/pet/:petId",
        requestFormat: "json",
        parameters: [
            {
                name: "petId", 
                type: "Path",
                schema: z.string().min(1).max(10).required()
            }, {
                name: "XCorrelationID",
                type: "Header",
                schema: z.string().min(36).max(256).required()
            }
        ],
        response: Pet,
    },
    {
        method: "put",
        path: "/pet/:petId",
        description: `Update an existing pet by Id`,
        requestFormat: "json",
        parameters: [
            {
                name: "petId", 
                type: "Path",
                schema: z.string().min(1).max(10)
            }, {
                name: "XCorrelationID",
                type: "Header",
                schema: z.string().min(36).max(256)
            },
            {
                name: "body",
                type: "Body",
                schema: Pet,
            },
        ],
        response: Pet,
    },
]);
```
 

Here is a reduced OpenAPI to reproduce the behaviour via https://openapi-zod-client.vercel.app

```yaml
openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /pet/:petId:
    parameters:
    - name: petId
      in: path
      description: |-
        Identifier of the pet
      required: true
      schema:
        maxLength: 10
        minLength: 1
        type: string
    - name: X-Correlation-ID
      in: header
      schema:
        minLength: 36
        maxLength: 256
        type: string
      required: true
    get:
      operationId: getPetById
      responses:
        200:
          application/json:
            schema:
                $ref: "#/components/schemas/Pet"
    put:
      operationId: updatePetById
      summary: Update an existing pet
      description: Update an existing pet by Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /otherPets/:petId:
    parameters:
    - name: petId
      in: path
      description: |-
        Identifier of the pet
      required: true
      schema:
        maxLength: 10
        minLength: 1
        type: string
    get:
      operationId: getOtherPetById
      responses:
        200:
          application/json:
            schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        category:
          $ref: "#/components/schemas/Category"
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: "#/components/schemas/Tag"
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: pet
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      xml:
        name: category
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
```

**Comment by mjour** [comment]
An "Invalid generated makeApi endpoints object" error typically occurs when there is an issue with the way the API endpoints are being created. The error message "if path specific parameters are defined" suggests that there is a problem with the way parameters are being passed in the path of the endpoint.

Here are a few possible causes and solutions for this error:

1. Missing or incorrect parameter names: Make sure that the parameter names specified in the path of the endpoint match the names of the parameters being passed in the function.

2. Incorrect parameter order: Ensure that the parameters are passed in the correct order as defined in the endpoint path.

3. Extra parameters being passed: Verify that only the required parameters are being passed to the endpoint.

4. Not passing required parameters: Make sure that all required parameters are passed to the endpoint.

5. Incorrect parameter type: Verify that the correct data type is being passed for each parameter.

6. Incorrectly formated path: Check the path of the endpoint, it may be that the endpoint path is not formatted correctly.

7. Incorrectly defined path: Verify that the endpoint path is defined correctly in the codebase.

It's hard to say exactly what the problem is without more information, but the above suggestions should help you troubleshoot the issue.

It would be good idea to check the documentation of the library or framework you are using for more information on how to format the endpoint path and pass the parameters correctly.

**Comment by astahmer** [comment]
hey, by quickly looking it seems that [this PR](https://github.com/astahmer/openapi-zod-client/pull/74) introduced the issue since I can reproduce on [the preview deployment associated](https://openapi-zod-client-gtvp8tqln-astahmer.vercel.app/?doc=PYBwpgdghiCWBcACAzAOgAyuQKFhAZsPNoogC6xkA2YSAygO5QDmzYATogAphkDOZYOzCIAtIgDy4CAEEuASRQYSiACZg%2BAY3awQFYBCQAfUStIAVABaw%2BiG4iiI%2BUALYga3XojqDh3jgBuHIgARlB8YKqIBuSWIlKQcopo6E7gmrD4sJpQ%2BhCopACawACuiDkQiFkQUaVkiC5CIlAhdWbeTKzBuYgA2pZkZCB88AD0o3ydbOyosMAAugAUA0Mj45Ms07PAAJQF8pVkcbGw7FGUHLlzlcD4sSLg9QJNADSIDGAA5EFODJSacSignuag0sGYlSy7AEDhAIHYwCgAIAhO1imUKogIMAGIg4lQQIgSrZYG4ET8jiIku84pTOJRPrYQgBPBpQADWeGY5UsUAgbFswMpoOqlGudn4YCodyE5GAIM0wHUqHaVh6TGZbz%2BR3IpLAWpEmNJ8OAFOO1LwiDYEEuVDefKiYAAHiBgBEnMAXCJbiCbbj8GBciVhCTKhIZHQ0Nh2gB9eR3ZmlT5%2BKjAYCc-lVWXCxibYIAJgwo3DdEQhdSQWh4p9PH4vn190qmio2XZfTiwiWK2GY1GkUoQlQGy6MzmowA-MGqABebtrUaPZ7CIdTDjbUYBfMTVczZmuKh7RAyKhkDjQChBKiaxCJjF8xCpqBRAKwRzCgAGAFFVJREAA%2BRAABlESiWsl3iCMywwd8GkgMpQDyZEY2jUhSDoT0RGJMB8BKKgHzwdkRnacReisERa28etEGEV0%2BAHdhmS7QYe3GZhKEsEoQlQRUXG3PN2FEGBYD4kdREXesdmIvoyI9YNNCpBQRTwMUYkIThhQonwmiY1ZezYo5OO4z0ROmQS4BMjgxN4cDRhCVMQlGFxwlPdgJnYTRHKgPBRhDUp3I0UZQEgITUD3FwDxUFyXD4CR8DoQJsloPFmN7YctjHKK%2BFGFRFQgMgkTIYhUMQMAnNgKgkCE09XAAATStc5hUFt5IgCIitQ6AvSQGQQCRY5y3aKckG7XsGDG1AYD6sBUCEZhRmayAIiywD5AAYU-AA5OhP1EctUAGcKVErOiDCQABGDBUDOs7sGdFzoCoAARYBNCI0h1C0HQ9GuJAADE8FqEp6kaPwWjqDp%2BJUIbkqGVKd22bAInYY72vEaG517cSmjQerR2AUYhI3HB8uYN6xCxVwksedoPu0XQ8iQT9K2ZI4uQcVogZvPzPH4do7rPKAnpesnitpr6GcQf6amiTmQbAdpSHRlL1nhxrSHETqkvAmmNDp77TqPTR5L4QV5TAqihHUaE%2Bade7Bee172tF3XxZ%2ByWAZl4GmnZ8Hue14rFfYCqYZAOH%2BIR9WKa6okkZ1z76bdhJ2CuAxbDBzmsPYbBeqOMmF14UZ4EeeRVCdxBeuTr0XJF8nNaQYvVAVuxDHL3JLCbsWE4Nkwm9IEvIAoLJgh9YVqYD6iwAARxKU5IiQMh2BKeXx60OInLL4qnKdQDIGYI5zvQXuGjwHf%2BX3xAbvH0gyGZcAkAEHR%2BSkuvEAADVEVahGEKgU4gUR5Eek3PAw1AxWybqvUqUAN6oRcCfXe59kAADYj5b1PnvSwSB8wAFZkFX3ILfLWC8uRN2ENPWepdyCL2XqhNghUm5BWTnkEuSBaG1gAELMhLiQjQrpWoaGgaQfM6B0ACNQjAdw2Rf6jAAFZ8FOkfYqED14KKvgAEmEPgJAAAiAAxKMHivCB5ZSUeEUYtYtHtBAEDaBDDf7MKJCAVQuQwDsM4Y3FeJQXBOQYkgAAqo45xDhKjOhsBQTMY8A6d31i3fxTjTxBJKk6UJbNHihFZFw8epCl4CDYUqZkojcqnjyqI0g4jmpSNkfIvBiiASQJKQHdR2FtF6IMQYIxExalOSyuY7hfBeFLVEVooR6AtH1KiRLOgJQjYaD4DhPCti8gqMKQPeppS4TlLyDIuRhgVE1LXlA3ZDSNHNP0Z6QxeVjGdNMT00ggU6RgULg3MuFdKbVzLhrSm9deAZIDsA1uRwO4uy7i3HueD%2B55UyLAYedxR68G4WQ4QFCF5L3AVc0RqD4EYIvofPBsCIBoPPpfK%2BN875OCIU-YqtCbHgEYdcextCJD3N4Bwn5xUQz9P4UfYZ9SymSM2ZUnZ1TUImNWUcppiBdGnLcG0i5HT9ndN4BY1pNoLntRMTXWs0CsnkNER8r0R9xAgEsMAQQvig58CbiSpKwAQjSLAJoMgTcTQ0ooJyvBsBS4qKtUgPAp5pgqLUk5QqzcyCIIACwqOdK4dwSUzo4qvnXL1BD77kuYJGp00aaBIFUMAVgUKj45D9UIfJKjGmaIlS0s5Mr%2BBysgVlVazjmDFosXgo1JrgBmqoDXce3qHDsGTsyFRTpwqioYMnOEc9KEoqFRcaKore0P2IUK0gw6KqHNIC-Ntpqg5HxJt2gOvaoD9qgIOoVq7R3jvAEiqhKjZ37vHmWk5yr2nqtGOYFgLar4CCDPe1CC7U0qPGW7VJ36yDEmbiCf21S4IuFFeIKAAQvI-zstQoVhrIA-gpcu8QciqDuIDueo%2Bm64XFQbUWnxlrk3RFtfax149nUcFdb%2Bj19Te2%2BrAP6oVgbcg%2BryuG9NmbY1Ec%2BUm0li6sN4KjW4LNiBnqkyboRvBL9C0ceLaqFg0De02rtQ6p1CIXVQuY56oVbG8ocY4AGoQQbeOhojUpkTJmqPibTePRTCbPnkBYEAA)

i'll investigate later, unless you are already on it ?

**Comment by pkoo** [comment]
Unfortunately not, I just can see/confirm that #74 introduced the issue.

Hope that I can get some spare time to also dig deeper into the library - and hopefully add this as a feature.

**Comment by pkoo** [comment]
Yes, I tested it with quite a large API and it looks good to me.

I also did a review of your changes and added two suggestions, hope that is okay for you.

Definitely a big thank you for your fast response and change proposal!

**Comment by astahmer** [comment]
great ! and thank you for both the review & the sponsor ! 🙏 

just pushed the changes you asked, if it's fine with you we can merge
